<a href="https://colab.research.google.com/github/yazminantunez12/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy es la libreria de pyhton.
NumPy se utiliza para trabajar con matrices o arreglos.
NumPy es la abreviatura de "python numerico"
Tambien tiene funciones para trabajar en el dominio del algebra lineal, la transformada y las matrices.
En python tenemos listas que sirven como matrices, pero son lentas de procesar.
NumPy tiene como objetivo proporcionar un objeto de matriz que sea 50 veces mas rapido que las listas tradicionales.

In [1]:
#Primero tenemos que importar la libreria
import numpy

arreglo = numpy.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


NumPy como np NumPy generalmente se importa bajo el alias np.
En python los alias son un nombre alternativo para referirse a la misma cosa.

In [5]:
import numpy as np

arreglo = np.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


Comprobando la version de NumPy la cadena de la version se almacena en atributo __version__

In [7]:
import numpy as np
print(np.__version__)

2.0.2


NumPy creando matrices Crear un objeto ndarray de NumPy.
NumPy se utiliza para trabajar con matrices.
El objetivo de matriz se llama ndarray
Podemos crear un NumPy ndarray utilizando la funcion()

In [9]:
import numpy as np
arreglo=np.array(["yazmin","Ana","kimberly","marisol"])
print(arreglo)
print(type(arreglo))

['yazmin' 'Ana' 'kimberly' 'marisol']
<class 'numpy.ndarray'>


Dimensiones en matrices
Una dimension en matrices es un nivel de profundidad de matriz(matrices
anidadas)
Una matriz anidada continen matrices como elementos.
Matrices 0-D. Son elementos de una matriz. cada valor de una matriz es una matriz 0.D. Ejemplo: Crea una matriz 0.D con un valor de 42.

In [10]:
import numpy as np
arreglo=np.array(42)
print(arreglo)

42


Matrices 1-D
Una matriz que tiene matrices 0-D como elementos se demonima matriz unidimensional o 1.D
Estas son matrices mas comunes y basicas.
Ejemplo: Crea una matriz de una dimension que tenga valores 1,2,3,4,5

In [11]:
import numpy as np
arreglo=np.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


Matrices de 2 dimensiones una matriz que tiene matrices 1-D como elementos se denomina matriz 2-D.
A menudo se utilizan para representar matrices de segundo orden.
NumPy tiene como submodulo completi dedicado a observaciones con matrices llamada numpy.mat Ejemplo: Crea una matriz de 2-D que contenga 2 matrices con los valores 123 y 456.

In [12]:
import numpy as np
arreglo=np.array([[1,2,3],[4,5,6]])
print(arreglo)

[[1 2 3]
 [4 5 6]]


Matrices 3D
Una matriz que tiene 2D se denomina matriz 3D,
estas matrices se utilizan para representar una matriz de tercer orden.
Ejemplo: Crea una matriz 3D con dos matrices bidimensionales, conteniendo dos matrices con los valores 1,2,3 y 4,5,6.

In [13]:
import numpy as np
arreglo=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
